// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatToEat.App.Storage;

#nullable disable

namespace WhatToEat.App.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20230416113029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("WhatToEat.App.Storage.Model.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoteDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoteDate");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("WhatToEat.App.Storage.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhatToEat.App.Storage.Model.Vote", b =>
                {
                    b.Property<long>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("WhatToEat.App.Storage.Model.Restaurant", b =>
                {
                    b.HasOne("WhatToEat.App.Storage.Model.Vote", null)
                        .WithMany("Restaurants")
                        .HasForeignKey("VoteDate");
                });

            modelBuilder.Entity("WhatToEat.App.Storage.Model.Vote", b =>
                {
                    b.HasOne("WhatToEat.App.Storage.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatToEat.App.Storage.Model.Vote", b =>
                {
                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
